### ISSUE TITLE
Pull in content from Command Line Basics Pt 1

### ISSUE THREAD

**Issue by zspencer** [zincmade/just-enough-unix-command-line#1]

**Comment by jessicard** [comment]
How are we structuring this repo? Just a bunch of markdown files?

**Comment by zspencer** [comment]
@jessicard good question. I'll create an issue to spike using pandoc to generate an ePub/Mobi just so we can have an idea how to structure it.

I'd recommend (in the meantime) having an `src` folder so in the event that we need to do some fancy-pants scripting to get things publishable we can make sure we're not polluting the src with build artifacts.

Zee
